version: 2

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
    tab-width: 1
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: websocket\.go
      linters:
        - gocyclo
    - path: examples/
      linters:
        - errcheck
        - gocritic
        - gosec
    - path: client\.go
      text: "G304.*Potential file inclusion"
      linters:
        - gosec
    - linters:
        - lll
      source: "^//go:generate "

run:
  timeout: 5m
  exclude-dirs:
    - examples
    - vendor
